name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-07"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWJhNGQzZmItNDIzMy00NDZhLWFlY2YtNGJlMTRmMDdhMWQzIiwidGVuYW50X2lkIjoiNTE3MWJiMDNmZjIxZmQxMTRhNmM4ZjVlYmVlYTRlNjUxZTY1Zjg2NjdkOGE3ZDJlNDViMTRhY2ExNmY2OTQwMyIsImludGVybmFsX3NlY3JldCI6ImY1MTU4NDczLTE4OTAtNDYxMC1iNWQ4LWZhM2E5MWIzM2E5ZCJ9.oJga22rAEKP25vWmmSb0GTC_2lQIVzeYimlrmzE9r_E"
JWT_TOKEN = "SECRETKEY"